### ISSUE TITLE
"Maybe later" button stops working on user logout

### ISSUE THREAD

**Issue by joseEkcit** [paviliondev/discourse-custom-wizard#150]
Hi!

I have noticed that login out of Discourse while the wizard is open breaks the "Maybe later" button.

This is the error in browser logs when clicking on the button:

![image](https://user-images.githubusercontent.com/66950991/137140598-4a764ef5-a128-436a-9323-0c120c05eae2.png)

**Comment by fzngagan** [comment]
@joseEkcit 
I'm working on a PR for this fix. Should be merged soon.
cc @angusmcleod

**Comment by joseEkcit** [comment]
Thank you for the nice work!
