### ISSUE TITLE
Time Issue when using with discourse-events

### ISSUE THREAD

**Issue by timmsantos** [paviliondev/discourse-custom-wizard#168]
Hi paviliondev,

When adding a Time with discourse-events within discourse-custom-wizard, the time always defaults to something else. No matter what timezone or time I put, this is always the output of the fields:
`{“timezone”=>“”, “all_day”=>“false”, “start”=>“2021-12-20T23:00:00.000Z”}`

One thing I noticed is that discourse-events does not have a drop down like when you create an event through a new topic, and works as expected by itself (discourse-events that is) which leads me to believe that the issue is it's compatibility with discourse-custom-wizard

**Comment by timmsantos** [comment]
After further investigating, I noticed the drop down is `.ui-timepicker-wrapper` and it doesn't show up in discourse-custom-wizard

**Comment by angusmcleod** [comment]
@timmsantos Thanks for raising this. We'll take a look within the next week.

**Comment by timmsantos** [comment]
Thank you @angusmcleod !

**Comment by timmsantos** [comment]
Hey @angusmcleod ,

Happy new year! Hope you are well.

Is there any update on this by any chance?

**Comment by angusmcleod** [comment]
Bumping this (for myself)
