### ISSUE TITLE
user TL can't be lower than poll_minimum_trust_level_to _create

### ISSUE THREAD

**Issue by izzy808** [paviliondev/discourse-custom-wizard#171]
if a user with TL lower than `poll_minimum_trust_level_to_create` submits a wizard that contains polls in the generated output, the post will appear in topic lists with -1 replies, and loading the topic results in this error:

```
":(
Error
Something went wrong."
```

wizard logs output:

`wizard: application; action: create_topic; user: X; error: failed to create - You are not allowed to create polls.`

**Comment by angusmcleod** [comment]
@izzy808 Thanks for this report, we'll address it asap
