### ISSUE TITLE
dropdown is broken

### ISSUE THREAD

**Issue by an-ant0ni0** [paviliondev/discourse-custom-wizard#184]
Since #175 the dropdown field type is not working anymore.

I figured out the adding of this function caused the issue: 
https://github.com/paviliondev/discourse-custom-wizard/blob/729442a289a3020b4d0d6ff4adf9bb3f55e8e280/serializers/custom_wizard/wizard_field_serializer.rb#L104-L106

As there is already a `def content` needed by the dropdown.
I'm not sure if it should be `def tags_groups` so I'm not providing an PR.

Thank you.

**Comment by Fma965** [comment]
@an-ant0ni0 Just to let you know this should be working now (and is working from my testing) thanks to the PR i submitted which was merged in to main branch

NOTE: I'm not part of the development of this plugin

**Comment by an-ant0ni0** [comment]
It is working again. Thanks a lot!
