### ISSUE TITLE
All features seem to be treated as subscription only

### ISSUE THREAD

**Issue by akhmerov** [paviliondev/discourse-custom-wizard#205]
I have the latest version of the wizard installed (0b4c1544, discourse at `latest-release +22`) and no subscription plugin / no activated subscription. When trying to create a new wizard with only one step and no input I see an error message "step index is subscription only"

![image](https://user-images.githubusercontent.com/2069677/195071421-29e50067-2696-4c26-8de3-41073bd57f45.png)

Because the wizard creation form clearly indicates that some features are subscription-only, I believe that this error message is due to an incorrect check. If, however, all features are subscription-only, please indicate it in the wizard creation form.

**Comment by angusmcleod** [comment]
Thanks @akhmerov yes, this is a bug. Sorry for the inconvenience! We'll be pushing a fix tomorrow.

**Comment by angusmcleod** [comment]
@akhmerov This is addressed in `2.0.4`.

**Comment by angusmcleod** [comment]
Yes, that's intended. I believe you successfully applied for a community subscription (?) which will give you access to that feature.
