### ISSUE TITLE
Emoji within step description breaks wizard

### ISSUE THREAD

**Issue by FerrariFlunker** [paviliondev/discourse-custom-wizard#223]
Hello!  Stumbled across this issue after our most recent update:

We had a :grin: emoji in the description of step 5 of our wizard.  Users would reach step 4, but wouldn't be able to progress to step 5.  An error shows in the console of the browser (I don't have it, sorry), but no indication of an issue is shown in the UI.

Removing the emoji from the description fixed the issue, and allowed the user to submit their wizard.

We're running wizard plugin v2.2.2 and discourse v3.1.0.beta2 [52d4de7b45](https://github.com/discourse/discourse/commits/52d4de7b45eb1b7c7997da2ba8bff83a3c22a3a5)

**Comment by angusmcleod** [comment]
Hello! Thanks for the report. I've posted this in our support inbox. We don't monitor issues closely and will be closing them soon. See the ticket here.

https://coop.pavilion.tech/t/emoji-within-step-description-breaks-wizard/2547
