### ISSUE TITLE
<!DOCTYPE html> error at the top

### ISSUE THREAD

**Issue by FuraXx** [paviliondev/discourse-custom-wizard#41]
Hello, I get an error when I validate step 1. see the attached screenshot
![Screenshot_11](https://user-images.githubusercontent.com/33160388/82810144-05ea3080-9e8e-11ea-991c-8e1300683df0.png)

my config: 
![Screenshot_12](https://user-images.githubusercontent.com/33160388/82810282-53669d80-9e8e-11ea-8c50-64c01284a1f6.png)

now I no longer have the error when I validate but I get another error:
![Screenshot_13](https://user-images.githubusercontent.com/33160388/82810324-6f6a3f00-9e8e-11ea-904b-aa9753296048.png)

after profil update:
![image](https://user-images.githubusercontent.com/33160388/82810864-ce7c8380-9e8f-11ea-9e7c-2cde3973f750.png)

**Comment by angusmcleod** [comment]
@FuraXx Hey, it looks like the wizard is working correctly. The ``Refused to load script`` error is unconnected with the custom wizard plugin.

The reason you're seeing ``t`` in the user profile is that you've mapped ``bio_raw`` to the checkbox field ``You are developer``. Checkbox fields are booleans, so ``t`` will show up in the profile if it's checked.

**Comment by angusmcleod** [comment]
@IwishIcanFLighT Hey, sorry for the slow reply. Are you still getting this error? Are you using the latest version of the plugin?

**Comment by IwishIcanFLighT** [comment]
@angusmcleod Thanks for getting back to me.

Yes I'm still facing the error and my Discourse instance is using the plugin & Discourse versions I mentioned in my previous message (Discourse: 2.9.0.beta3 (fc40a572bb) & plugin: 1.18.4). I believe they both are up-to-date.

Tried on both Firefox and Chrome, same error.

Here's the 500 error console output:
```
XHRPUThttps://mydomain.com/w/my-wizard/steps/step_1
[HTTP/2 500 Internal Server Error 290ms]

	
PUT
	https://mydomain.com/w/my-wizard/steps/step_1
État
500
Internal Server Error
VersionHTTP/2
Transfert0,99 Ko (taille 658 o)
Politique de référentstrict-origin-when-cross-origin

    	
    content-length
    	658
    content-type
    	text/html; charset=utf-8
    date
    	Tue, 12 Apr 2022 09:25:40 GMT
    server
    	openresty
    set-cookie
    	__profilin=*Hidden for privacy*; path=/; secure; HttpOnly; SameSite=Lax
    X-Firefox-Spdy
    	h2
    x-request-id
    	6f3f7bd8-2c0d-4748-8b4d-5c314537ebbc
    x-runtime
    	0.267575
    	
    Accept
    	*/*
    Accept-Encoding
    	gzip, deflate, br
    Accept-Language
    	fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
    Cache-Control
    	no-cache
    Connection
    	keep-alive
    Content-Length
    	148
    Content-Type
    	application/x-www-form-urlencoded; charset=UTF-8
    Cookie
		*Hidden for privacy*
	Host
    	mydomain.com
    Origin
    	https://mydomain.com
    Pragma
    	no-cache
    Referer
    	https://mydomain.com/w/my-wizard/steps/step_1
    Sec-Fetch-Dest
    	empty
    Sec-Fetch-Mode
    	cors
    Sec-Fetch-Site
    	same-origin
    TE
    	trailers
    User-Agent
    	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0
    X-CSRF-Token
    	*Hidden for privacy*
    X-Requested-With
    	XMLHttpRequest
```

**Comment by angusmcleod** [comment]
The issue is most likely specific to the wizard you have. Could you please export the wizard seeing this error (in the wizard manager) and PM it to me on coop.pavilion.tech? Thanks.
