### ISSUE TITLE
Conflict with new version of Discourse

### ISSUE THREAD

**Issue by orhanasan** [paviliondev/discourse-custom-wizard#43]
A new commit that can be seen [here](https://github.com/discourse/discourse/commit/62ad4737162adfe0a139d497efcebec55ddb6554) made our wizards not working at all (basically wizards are not loading in submission view). Error can be seen in this image.
![image](https://user-images.githubusercontent.com/29615984/84570585-0f80fd00-ad97-11ea-8298-ad523543729c.png)

**Comment by angusmcleod** [comment]
Hey @orhanasan, thanks for the report

We ensure our open source plugins work with the latest discourse in the first week of every month. The next support period is July 1 to 5.

That said, I'll take a look at this this week and push a fix, however it will need to be a bit later in the week. I'll ping you here when I push it.
