### ISSUE TITLE
A question about custom field (from code)

### ISSUE THREAD

**Issue by psychedel** [paviliondev/discourse-custom-wizard#71]
Hi,
I'm trying to fix [national-flags](https://github.com/Ebsy/discourse-nationalflags) to work again with the custom wizard.

During the registration:
```
DiscourseEvent.on(:custom_wizard_ready) do
  if defined?(CustomWizard) == 'constant' && CustomWizard.class == Module
    CustomWizard::Field.register('national-flag', 'discourse-nationalflags', ['components', 'templates'])
    CustomWizard::UpdateValidator.add_field_validator('national-flag') do |field, updater, step_template|
      if step_template['actions'].present?
        step_template['actions'].each do |a|...
```
It has a problem as there is no step_template['actions'] at all. So the field can't be processed.

Is there a short fix for that?
Or things were completely changes on the custom wizard side and I need to deep into it?
Thanks!

**Comment by fzngagan** [comment]
Hi @4ong 
I'm starting an internal discussion on this.

**Comment by fzngagan** [comment]
@4ong 
The issue has been fixed. Check out here
https://meta.discourse.org/t/national-flags-display-user-nationality-in-discourse/55969/105

**Comment by 4ong** [comment]
Thank @fzngagan awesome! I will also learn from the solution how the fix works!
